<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

define('NYHSDORA_AMERICAN_EXPERIENCE_PID', 'islandora:american_experience');
define('NYHSDORA_MAPS_PID', 'islandora:maps');
define('NYHSDORA_BROADSIDE_PID', 'islandora:broadside');

/**
 * Implements hook_islandora_required_objects().
 */
function nyhsdora_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'nyhsdora');
  $islandora_path = drupal_get_path('module', 'islandora');
  $collections = array(
    NYHSDORA_AMERICAN_EXPERIENCE_PID => array(
      'pid' => NYHSDORA_AMERICAN_EXPERIENCE_PID,
      'title' => 'Witness to the Early American Experience',
    ),
    NYHSDORA_MAPS_PID => array(
      'pid' => NYHSDORA_MAPS_PID,
      'title' => 'Maps',
      'parent' => NYHSDORA_AMERICAN_EXPERIENCE_PID,
    ),
    NYHSDORA_BROADSIDE_PID => array(
      'pid' => NYHSDORA_BROADSIDE_PID,
      'title' => 'Broadside',
      'parent' => NYHSDORA_AMERICAN_EXPERIENCE_PID,
    ),
  );
  $objects = array();
  foreach ($collections as $info) {
    $collection = $connection->repository->constructObject($info['pid']);
    $collection->owner = 'fedoraAdmin';
    $collection->label = $info['title'];
    $parent = isset($info['parent']) ? $info['parent'] : 'islandora:root';
    $collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', $parent);
    $collection->models = 'islandora:collectionCModel';

    // Collection Policy Datastream.
    $policy_datastream = $collection->constructDatastream('COLLECTION_POLICY', 'X');
    $policy_datastream->label = 'Islandora Collection Policy';
    $policy_datastream->mimetype = 'application/xml';
    $policy_datastream->setContentFromFile("$module_path/xml/nyhs_collection_policy.xml", FALSE);
    $collection->ingestDatastream($policy_datastream);

    // TN Datastream.
    $datastream = $collection->constructDatastream('TN', 'M');
    $datastream->label = 'Thumbnail';
    $datastream->mimetype = 'image/png';
    $datastream->setContentFromFile("$islandora_path/images/folder.png", FALSE);
    $collection->ingestDatastream($datastream);

    $objects[] = $collection;
  }

  return array(
    'nyhsdora' => array(
      'title' => t('New York Historical Society'),
      'objects' => $objects,
    ),
  );
}


/**
 * Implements hook_contentdm_migration_tools_migrate_item_to_mods_transform().
 */
function nyhsdora_contentdm_migration_tools_migrate_item_to_mods_transform_alter(&$transform, array $data, &$params) {
  $path = drupal_realpath(drupal_get_path('module', 'nyhsdora') . '/transforms/cdm-api-export2MODS.xsl');
  $transform = $path;
  $current_collection = FALSE;
  switch ($params['alias']) {
    case 'p16124coll1':
      $current_collection = 'AmericanManuscripts';
      break;

    case 'p16694coll47':
      $current_collection = 'CivilWarTreasures';
      break;

    case 'p15052coll5':
      $current_collection = 'SlaveryManuscripts';
      break;

    case 'NYHSR01':
      $current_collection = 'NYHSQuarterly';
      break;

    case 'p16124coll2':
      $current_collection = 'PhotosOfNYC';
      break;
  }
  $params['current-collection'] = $current_collection;
}

/**
 * Implements hook_contentdm_migration_tools_migrate_item().
 */
function nyhsdora_contentdm_migration_tools_migrate_item_alter(AbstractObject &$object, AbstractObject $parent, array $data, $update) {
  if (isset($object['MODS'])) {
    $dom = new DOMDocument();
    $dom->loadXML($object['MODS']->content);
    $dom_xpath = new DOMXPath($dom);
    $dom_xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
    $dom_xpath->registerNamespace('cdm', 'http://oclc.org/cdm');
    $full_text = $dom_xpath->evaluate('string(/mods:mods/mods:extension/cdm:fulltext/text())');
    if (!empty($full_text)) {
      module_load_include('inc', 'islandora', 'includes/utlities');
      $ds = $object->constructDatastream('FULL_TEXT', 'M');
      $ds->label = 'FULL_TEXT';
      $ds->mimetype = 'text/plain';
      $ds->content = islandora_sanitize_input_for_valid_xml($full_text);
      $object->ingestDatastream($ds);
    }
  }
}
