<?php

/**
 * @file
 * This file contains all install related hooks.
 */

/**
 * Implements hook_install().
 */
function nyhsdora_install() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('nyhsdora');
}

/**
 * Implements hook_uninstall().
 */
function nyhsdora_uninstall() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('nyhsdora', 'uninstall');
}
